### ISSUE TITLE
Injecting gremlins lib

### ISSUE THREAD

**Issue by y-lohse** [kupriyanenko/grunt-gremlins#5]
Hi, I have the following use case: I have a webpage I want to test, gremlins being only one of the tests. I however don't want to load the gremlins.js lib in that pages source because outside of the gremlins test, it makes no sense.
Would an option to inject the gremlins lib make sense? And if so would you be willing to do it / accept a PR for it?

**Comment by kupriyanenko** [comment]
Yes, you can do it, see [example in docs](https://github.com/kupriyanenko/grunt-gremlins#specific-targets-with-per-target-options). Task example for you:

```
gremlins: {
  mySiteTaskName: {
    options: {
      path: 'https://google.com',
      test: __dirname + '/examples/test.gremlins.js'
    }
  }
}
```

**Comment by y-lohse** [comment]
Sweet, I didn't get from the documentation that it would inject the lib as well, but it does. Thanks!

**Comment by kupriyanenko** [comment]
Great, will improve the documentation :)
